import sys
import os

# Add backend to sys path
sys.path.append(r"c:\Users\Admin\Documents\Resume\backend")

from app.services.chatbot_service import process_chat_query, engine, text, llm

print("Testing prompt generated by gemma2:9b")

query = "give me the list of jd"
print("Input:", query)
response = process_chat_query(query)
print("Response:", response)
